name: Cloud Foundry

on:
  workflow_call:
    inputs:
      cf-api:
        description: 'Cloud Foundry API endpoint'
        required: true
        type: string
      cf-org:
        description: 'Cloud Foundry organization'
        required: true
        type: string
      cf-space:
        description: 'Cloud Foundry space'
        required: true
        type: string
      environment:
        description: 'Deployment environment name'
        required: true
        type: string

  workflow_dispatch:
  merge_group:
  push:
    branches:
      - main

concurrency:
  group: cf-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  APP_NAME: samples
  FORCE_COLOR: true
jobs:
  deploy:
    runs-on: linux
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: ./.github/actions/cf-setup
        with:
          cf-api: ${{ inputs.cf-api || vars.CF_API }}
          cf-org: ${{ inputs.cf-org || vars.CF_ORG }}
          cf-space: ${{ inputs.cf-space || vars.CF_SPACE }}
          cf-username: ${{ vars.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
      - run: npm clean-install
      - run: npx cds up

      - uses: ./.github/actions/cf-github-deploy
        with:
          app-name: ${{ env.APP_NAME }}
          environment: ${{ inputs.environment || 'Staging' }}

      - run: cf logs ${{ env.APP_NAME }} --recent
      - run: cf logs orders-srv --recent
      - run: cf logs reviews-srv --recent
      - run: cf logs bookstore-srv --recent
      - run: cf logs ${{ env.APP_NAME }}-db-deployer --recent
