name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  tests:
    uses: capire/samples/.github/workflows/test.yaml@main
    secrets: inherit

  deploy-cf:
    needs: [tests]
    uses: capire/samples/.github/workflows/cf.yaml@main
    secrets: inherit
    with:
      cf-api: ${{ vars.CF_API_PRODUCTION }}
      cf-org: ${{ vars.CF_ORG_PRODUCTION }}
      cf-space: ${{ vars.CF_SPACE_PRODUCTION }}
      environment: Production
